name: "Public Support Collection"
pipelines:
  - slug: "add_slug_to_cohort_users_publicsupport"
    sources:
      - cohort-users
      - cohorts
    destination: cohort-users-with-slug
    transformations:
      - add_slug_to_cohort_users

  - slug: "add_slug_to_slack_messages_publicsupport"
    sources:
      - slack_support_channels
      - auth-user
      - cohort-users-with-slug
    destination: slack-support-channels-with-slug
    transformations:
      - add_slug_to_slack_messages

  - slug: "clean_questions_publicsupport"
    sources:
      - slack-support-channels-with-slug
      - public-support-agents
    destination: cleaned-questions-publicsupport
    transformations: 
      - new_columns
      - questions_dataframe
  
  - slug: "clean_answers_publicsupport"
    sources:
      - slack-support-channels-with-slug
      - public-support-agents
    destination: cleaned-answers-publicsupport
    transformations:
      - new_columns
      - answers_dataframe

  - slug: "merge_messages_publicsupport"
    sources:
      - cleaned-questions-publicsupport  
      - cleaned-answers-publicsupport   
    destination: cleaned-support-channels
    transformations:
      - merge_dataframes