name: "Public Support Collection"
pipelines:
  - slug: "clean_publicsupport_fs_messages"
    sources:
      - support_channels   
    destination: cleaned-support-channels
    transformations: 
      - new_columns
      - questions_dataframe
      - answers_dataframe
      - merge_dataframes