name: "Public Support Collection"
pipelines:
  - slug: "clean_publicsupport_fs_messages"
    sources:
      - support-channels   
    destination: cleaned-support-channels
    transformations: 
      - merge_messages
      # - transformation-2

