name: "Events Collection"
pipelines:
  - slug: "clean"
    sources:
      - support-channels   
    destination: cleaned-support-channels
    transformations: 
      - transformation-1
      - transformation-2

